### PR TITLE
926 account params not loading data

### LINKED ISSUE #926: Account params not loading data
when searching for a specific network, the page shows the information that is selected by default, and it shows the correct one until the user clicks the search button, that way it already shows the correct information.
Let's correct the error and display the information without the need for the button action

https://libre.eosio.online/accounts?account=stake.libre

image

### PR DESCRIPTION
**Pull request by fvives99**
### What does this PR do?

- Resolve #926

### Steps to test

1. Go to accounts and contracts
2. Search by query parameters `account` and `table` at `http://localhost:3000/accounts?account=stake.libre&table=stake` and refresh or open in a new window to verify account doesnt reset to EOSIO.

By default, when account isnt entered `eosio` will be loaded by default

#### CheckList

- [x] Fix query parameters not loading when entered by URL
- [x] Added matching shadow design from homepage
- [x] Added message when entered table doesnt exist

### CODE REVIEW

**Comment by fvives99** [comment]
Message when table doesn't exist

image

**Comment by fvives99** [comment]
Account and Table loaded after opening on new incognito window

image

**Review by tetogomez — APPROVED** [review]
LGTM

**Review by Torresmorah — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM

**Pull request merged**
