### PR TITLE
947 mobile footer redesign

### LINKED ISSUE #947: mobile footer redesign
I believe the mobile footer can be improved

image

### PR DESCRIPTION
**Pull request by fvives99**
### What does this PR do?

- Resolve #947 

### Steps to test

1. Open project
2. See footer on mobile

#### CheckList

- [x] Change layout row -> column
- [x] Change order when screen is resized

### CODE REVIEW

**Comment by fvives99** [comment]
Before:
image

After:
image

**Review by Edwinjrc — COMMENTED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM

**Review by Torresmorah — APPROVED** [review]
LGTM

**Pull request merged**
